package com.chensheng.dao;

import com.chensheng.model.EcsAdmin;
import java.util.List;

public interface EcsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin
     *
     * @mbg.generated
     */
    int insert(EcsAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin
     *
     * @mbg.generated
     */
    EcsAdmin selectByPrimaryKey(String adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin
     *
     * @mbg.generated
     */
    List<EcsAdmin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAdmin record);
}