package com.chensheng.dao;

import com.chensheng.model.EcsCityareas;
import java.util.List;

public interface EcsCityareasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cityareas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cityareas
     *
     * @mbg.generated
     */
    int insert(EcsCityareas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cityareas
     *
     * @mbg.generated
     */
    EcsCityareas selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cityareas
     *
     * @mbg.generated
     */
    List<EcsCityareas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cityareas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsCityareas record);
}