package com.chensheng.dao;

import com.chensheng.model.EcsDisscope;
import java.util.List;

public interface EcsDisscopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_disscope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer areasid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_disscope
     *
     * @mbg.generated
     */
    int insert(EcsDisscope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_disscope
     *
     * @mbg.generated
     */
    EcsDisscope selectByPrimaryKey(Integer areasid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_disscope
     *
     * @mbg.generated
     */
    List<EcsDisscope> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_disscope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsDisscope record);
}