package com.chensheng.dao;

import com.chensheng.model.EcsDistribution;
import java.util.List;

public interface EcsDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distribution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distribution
     *
     * @mbg.generated
     */
    int insert(EcsDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distribution
     *
     * @mbg.generated
     */
    EcsDistribution selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distribution
     *
     * @mbg.generated
     */
    List<EcsDistribution> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsDistribution record);
}