package com.chensheng.dao;

import com.chensheng.model.EcsOrders;
import java.util.List;

public interface EcsOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_orders
     *
     * @mbg.generated
     */
    int insert(EcsOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_orders
     *
     * @mbg.generated
     */
    EcsOrders selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_orders
     *
     * @mbg.generated
     */
    List<EcsOrders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsOrders record);
}