package com.chensheng.dao;

import com.chensheng.model.EcsProvinces;
import java.util.List;

public interface EcsProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_provinces
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_provinces
     *
     * @mbg.generated
     */
    int insert(EcsProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_provinces
     *
     * @mbg.generated
     */
    EcsProvinces selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_provinces
     *
     * @mbg.generated
     */
    List<EcsProvinces> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_provinces
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsProvinces record);
}