package com.chensheng.dao;

import com.chensheng.model.EcsReceipt;
import java.util.List;

public interface EcsReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_receipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String startcity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_receipt
     *
     * @mbg.generated
     */
    int insert(EcsReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_receipt
     *
     * @mbg.generated
     */
    EcsReceipt selectByPrimaryKey(String startcity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_receipt
     *
     * @mbg.generated
     */
    List<EcsReceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_receipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsReceipt record);
}