package com.chensheng.dao;

import com.chensheng.model.EcsUser;
import java.util.List;

public interface EcsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user
     *
     * @mbg.generated
     */
    int insert(EcsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user
     *
     * @mbg.generated
     */
    EcsUser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user
     *
     * @mbg.generated
     */
    List<EcsUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsUser record);
}