package com.chensheng.model;

public class EcsAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.adminID
     *
     * @mbg.generated
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.userID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.astate
     *
     * @mbg.generated
     */
    private Integer astate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.acity
     *
     * @mbg.generated
     */
    private String acity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.aphone
     *
     * @mbg.generated
     */
    private String aphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.adminID
     *
     * @return the value of ecs_admin.adminID
     *
     * @mbg.generated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.adminID
     *
     * @param adminid the value for ecs_admin.adminID
     *
     * @mbg.generated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.name
     *
     * @return the value of ecs_admin.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.name
     *
     * @param name the value for ecs_admin.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.sex
     *
     * @return the value of ecs_admin.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.sex
     *
     * @param sex the value for ecs_admin.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.userID
     *
     * @return the value of ecs_admin.userID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.userID
     *
     * @param userid the value for ecs_admin.userID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.astate
     *
     * @return the value of ecs_admin.astate
     *
     * @mbg.generated
     */
    public Integer getAstate() {
        return astate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.astate
     *
     * @param astate the value for ecs_admin.astate
     *
     * @mbg.generated
     */
    public void setAstate(Integer astate) {
        this.astate = astate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.acity
     *
     * @return the value of ecs_admin.acity
     *
     * @mbg.generated
     */
    public String getAcity() {
        return acity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.acity
     *
     * @param acity the value for ecs_admin.acity
     *
     * @mbg.generated
     */
    public void setAcity(String acity) {
        this.acity = acity == null ? null : acity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.address
     *
     * @return the value of ecs_admin.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.address
     *
     * @param address the value for ecs_admin.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.pwd
     *
     * @return the value of ecs_admin.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.pwd
     *
     * @param pwd the value for ecs_admin.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.aphone
     *
     * @return the value of ecs_admin.aphone
     *
     * @mbg.generated
     */
    public String getAphone() {
        return aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.aphone
     *
     * @param aphone the value for ecs_admin.aphone
     *
     * @mbg.generated
     */
    public void setAphone(String aphone) {
        this.aphone = aphone == null ? null : aphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.note
     *
     * @return the value of ecs_admin.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.note
     *
     * @param note the value for ecs_admin.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}