package com.chensheng.model;

public class EcsCityareas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cityareas.aId
     *
     * @mbg.generated
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cityareas.aName
     *
     * @mbg.generated
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cityareas.cityID
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cityareas.aId
     *
     * @return the value of ecs_cityareas.aId
     *
     * @mbg.generated
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cityareas.aId
     *
     * @param aid the value for ecs_cityareas.aId
     *
     * @mbg.generated
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cityareas.aName
     *
     * @return the value of ecs_cityareas.aName
     *
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cityareas.aName
     *
     * @param aname the value for ecs_cityareas.aName
     *
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cityareas.cityID
     *
     * @return the value of ecs_cityareas.cityID
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cityareas.cityID
     *
     * @param cityid the value for ecs_cityareas.cityID
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }
}