package com.chensheng.model;

public class EcsCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_city.cId
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_city.cName
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_city.provincesID
     *
     * @mbg.generated
     */
    private String provincesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_city.cId
     *
     * @return the value of ecs_city.cId
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_city.cId
     *
     * @param cid the value for ecs_city.cId
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_city.cName
     *
     * @return the value of ecs_city.cName
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_city.cName
     *
     * @param cname the value for ecs_city.cName
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_city.provincesID
     *
     * @return the value of ecs_city.provincesID
     *
     * @mbg.generated
     */
    public String getProvincesid() {
        return provincesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_city.provincesID
     *
     * @param provincesid the value for ecs_city.provincesID
     *
     * @mbg.generated
     */
    public void setProvincesid(String provincesid) {
        this.provincesid = provincesid == null ? null : provincesid.trim();
    }
}