package com.chensheng.model;

public class EcsDisscope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_disscope.areasId
     *
     * @mbg.generated
     */
    private Integer areasid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_disscope.areasname
     *
     * @mbg.generated
     */
    private String areasname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_disscope.aprice
     *
     * @mbg.generated
     */
    private Long aprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_disscope.cId
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_disscope.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_disscope.areasId
     *
     * @return the value of ecs_disscope.areasId
     *
     * @mbg.generated
     */
    public Integer getAreasid() {
        return areasid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_disscope.areasId
     *
     * @param areasid the value for ecs_disscope.areasId
     *
     * @mbg.generated
     */
    public void setAreasid(Integer areasid) {
        this.areasid = areasid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_disscope.areasname
     *
     * @return the value of ecs_disscope.areasname
     *
     * @mbg.generated
     */
    public String getAreasname() {
        return areasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_disscope.areasname
     *
     * @param areasname the value for ecs_disscope.areasname
     *
     * @mbg.generated
     */
    public void setAreasname(String areasname) {
        this.areasname = areasname == null ? null : areasname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_disscope.aprice
     *
     * @return the value of ecs_disscope.aprice
     *
     * @mbg.generated
     */
    public Long getAprice() {
        return aprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_disscope.aprice
     *
     * @param aprice the value for ecs_disscope.aprice
     *
     * @mbg.generated
     */
    public void setAprice(Long aprice) {
        this.aprice = aprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_disscope.cId
     *
     * @return the value of ecs_disscope.cId
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_disscope.cId
     *
     * @param cid the value for ecs_disscope.cId
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_disscope.note
     *
     * @return the value of ecs_disscope.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_disscope.note
     *
     * @param note the value for ecs_disscope.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}