package com.chensheng.model;

public class EcsOrders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.oId
     *
     * @mbg.generated
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.oType
     *
     * @mbg.generated
     */
    private Integer otype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.handover
     *
     * @mbg.generated
     */
    private String handover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.youjiren
     *
     * @mbg.generated
     */
    private String youjiren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.maddress
     *
     * @mbg.generated
     */
    private String maddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.saddress
     *
     * @mbg.generated
     */
    private String saddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.ostate
     *
     * @mbg.generated
     */
    private Integer ostate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.mphone
     *
     * @mbg.generated
     */
    private String mphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.cphone
     *
     * @mbg.generated
     */
    private String cphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.startcity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.middlecity
     *
     * @mbg.generated
     */
    private String middlecity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.endcity
     *
     * @mbg.generated
     */
    private String endcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.sprice
     *
     * @mbg.generated
     */
    private Long sprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.pprice
     *
     * @mbg.generated
     */
    private Long pprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.yprice
     *
     * @mbg.generated
     */
    private Long yprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.zprice
     *
     * @mbg.generated
     */
    private String zprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.vehicle
     *
     * @mbg.generated
     */
    private String vehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_orders.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.oId
     *
     * @return the value of ecs_orders.oId
     *
     * @mbg.generated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.oId
     *
     * @param oid the value for ecs_orders.oId
     *
     * @mbg.generated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.oType
     *
     * @return the value of ecs_orders.oType
     *
     * @mbg.generated
     */
    public Integer getOtype() {
        return otype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.oType
     *
     * @param otype the value for ecs_orders.oType
     *
     * @mbg.generated
     */
    public void setOtype(Integer otype) {
        this.otype = otype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.handover
     *
     * @return the value of ecs_orders.handover
     *
     * @mbg.generated
     */
    public String getHandover() {
        return handover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.handover
     *
     * @param handover the value for ecs_orders.handover
     *
     * @mbg.generated
     */
    public void setHandover(String handover) {
        this.handover = handover == null ? null : handover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.name
     *
     * @return the value of ecs_orders.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.name
     *
     * @param name the value for ecs_orders.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.weight
     *
     * @return the value of ecs_orders.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.weight
     *
     * @param weight the value for ecs_orders.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.youjiren
     *
     * @return the value of ecs_orders.youjiren
     *
     * @mbg.generated
     */
    public String getYoujiren() {
        return youjiren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.youjiren
     *
     * @param youjiren the value for ecs_orders.youjiren
     *
     * @mbg.generated
     */
    public void setYoujiren(String youjiren) {
        this.youjiren = youjiren == null ? null : youjiren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.maddress
     *
     * @return the value of ecs_orders.maddress
     *
     * @mbg.generated
     */
    public String getMaddress() {
        return maddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.maddress
     *
     * @param maddress the value for ecs_orders.maddress
     *
     * @mbg.generated
     */
    public void setMaddress(String maddress) {
        this.maddress = maddress == null ? null : maddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.saddress
     *
     * @return the value of ecs_orders.saddress
     *
     * @mbg.generated
     */
    public String getSaddress() {
        return saddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.saddress
     *
     * @param saddress the value for ecs_orders.saddress
     *
     * @mbg.generated
     */
    public void setSaddress(String saddress) {
        this.saddress = saddress == null ? null : saddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.ostate
     *
     * @return the value of ecs_orders.ostate
     *
     * @mbg.generated
     */
    public Integer getOstate() {
        return ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.ostate
     *
     * @param ostate the value for ecs_orders.ostate
     *
     * @mbg.generated
     */
    public void setOstate(Integer ostate) {
        this.ostate = ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.mphone
     *
     * @return the value of ecs_orders.mphone
     *
     * @mbg.generated
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.mphone
     *
     * @param mphone the value for ecs_orders.mphone
     *
     * @mbg.generated
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.consignee
     *
     * @return the value of ecs_orders.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.consignee
     *
     * @param consignee the value for ecs_orders.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.cphone
     *
     * @return the value of ecs_orders.cphone
     *
     * @mbg.generated
     */
    public String getCphone() {
        return cphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.cphone
     *
     * @param cphone the value for ecs_orders.cphone
     *
     * @mbg.generated
     */
    public void setCphone(String cphone) {
        this.cphone = cphone == null ? null : cphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.startcity
     *
     * @return the value of ecs_orders.startcity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.startcity
     *
     * @param startcity the value for ecs_orders.startcity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.middlecity
     *
     * @return the value of ecs_orders.middlecity
     *
     * @mbg.generated
     */
    public String getMiddlecity() {
        return middlecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.middlecity
     *
     * @param middlecity the value for ecs_orders.middlecity
     *
     * @mbg.generated
     */
    public void setMiddlecity(String middlecity) {
        this.middlecity = middlecity == null ? null : middlecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.endcity
     *
     * @return the value of ecs_orders.endcity
     *
     * @mbg.generated
     */
    public String getEndcity() {
        return endcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.endcity
     *
     * @param endcity the value for ecs_orders.endcity
     *
     * @mbg.generated
     */
    public void setEndcity(String endcity) {
        this.endcity = endcity == null ? null : endcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.sprice
     *
     * @return the value of ecs_orders.sprice
     *
     * @mbg.generated
     */
    public Long getSprice() {
        return sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.sprice
     *
     * @param sprice the value for ecs_orders.sprice
     *
     * @mbg.generated
     */
    public void setSprice(Long sprice) {
        this.sprice = sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.pprice
     *
     * @return the value of ecs_orders.pprice
     *
     * @mbg.generated
     */
    public Long getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.pprice
     *
     * @param pprice the value for ecs_orders.pprice
     *
     * @mbg.generated
     */
    public void setPprice(Long pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.yprice
     *
     * @return the value of ecs_orders.yprice
     *
     * @mbg.generated
     */
    public Long getYprice() {
        return yprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.yprice
     *
     * @param yprice the value for ecs_orders.yprice
     *
     * @mbg.generated
     */
    public void setYprice(Long yprice) {
        this.yprice = yprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.zprice
     *
     * @return the value of ecs_orders.zprice
     *
     * @mbg.generated
     */
    public String getZprice() {
        return zprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.zprice
     *
     * @param zprice the value for ecs_orders.zprice
     *
     * @mbg.generated
     */
    public void setZprice(String zprice) {
        this.zprice = zprice == null ? null : zprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.vehicle
     *
     * @return the value of ecs_orders.vehicle
     *
     * @mbg.generated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.vehicle
     *
     * @param vehicle the value for ecs_orders.vehicle
     *
     * @mbg.generated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_orders.note
     *
     * @return the value of ecs_orders.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_orders.note
     *
     * @param note the value for ecs_orders.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}