package com.chensheng.model;

public class EcsProvinces {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_provinces.pId
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_provinces.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_provinces.pId
     *
     * @return the value of ecs_provinces.pId
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_provinces.pId
     *
     * @param pid the value for ecs_provinces.pId
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_provinces.pname
     *
     * @return the value of ecs_provinces.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_provinces.pname
     *
     * @param pname the value for ecs_provinces.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }
}