package com.chensheng.model;

import java.util.Date;

public class EcsReceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_receipt.startcity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_receipt.endcity
     *
     * @mbg.generated
     */
    private String endcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_receipt.arrivedcity
     *
     * @mbg.generated
     */
    private String arrivedcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_receipt.cstate
     *
     * @mbg.generated
     */
    private Integer cstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_receipt.generateday
     *
     * @mbg.generated
     */
    private Date generateday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_receipt.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_receipt.startcity
     *
     * @return the value of ecs_receipt.startcity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_receipt.startcity
     *
     * @param startcity the value for ecs_receipt.startcity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_receipt.endcity
     *
     * @return the value of ecs_receipt.endcity
     *
     * @mbg.generated
     */
    public String getEndcity() {
        return endcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_receipt.endcity
     *
     * @param endcity the value for ecs_receipt.endcity
     *
     * @mbg.generated
     */
    public void setEndcity(String endcity) {
        this.endcity = endcity == null ? null : endcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_receipt.arrivedcity
     *
     * @return the value of ecs_receipt.arrivedcity
     *
     * @mbg.generated
     */
    public String getArrivedcity() {
        return arrivedcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_receipt.arrivedcity
     *
     * @param arrivedcity the value for ecs_receipt.arrivedcity
     *
     * @mbg.generated
     */
    public void setArrivedcity(String arrivedcity) {
        this.arrivedcity = arrivedcity == null ? null : arrivedcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_receipt.cstate
     *
     * @return the value of ecs_receipt.cstate
     *
     * @mbg.generated
     */
    public Integer getCstate() {
        return cstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_receipt.cstate
     *
     * @param cstate the value for ecs_receipt.cstate
     *
     * @mbg.generated
     */
    public void setCstate(Integer cstate) {
        this.cstate = cstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_receipt.generateday
     *
     * @return the value of ecs_receipt.generateday
     *
     * @mbg.generated
     */
    public Date getGenerateday() {
        return generateday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_receipt.generateday
     *
     * @param generateday the value for ecs_receipt.generateday
     *
     * @mbg.generated
     */
    public void setGenerateday(Date generateday) {
        this.generateday = generateday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_receipt.note
     *
     * @return the value of ecs_receipt.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_receipt.note
     *
     * @param note the value for ecs_receipt.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}