package com.chensheng.model;

public class EcsRoute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.cId
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.pstartId
     *
     * @mbg.generated
     */
    private String pstartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.cstartId
     *
     * @mbg.generated
     */
    private String cstartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.pmiddleId
     *
     * @mbg.generated
     */
    private String pmiddleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.cmiddleId
     *
     * @mbg.generated
     */
    private String cmiddleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.pendId
     *
     * @mbg.generated
     */
    private String pendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.cendId
     *
     * @mbg.generated
     */
    private String cendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.yprice
     *
     * @mbg.generated
     */
    private Long yprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_route.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.cId
     *
     * @return the value of ecs_route.cId
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.cId
     *
     * @param cid the value for ecs_route.cId
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.cname
     *
     * @return the value of ecs_route.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.cname
     *
     * @param cname the value for ecs_route.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.pstartId
     *
     * @return the value of ecs_route.pstartId
     *
     * @mbg.generated
     */
    public String getPstartid() {
        return pstartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.pstartId
     *
     * @param pstartid the value for ecs_route.pstartId
     *
     * @mbg.generated
     */
    public void setPstartid(String pstartid) {
        this.pstartid = pstartid == null ? null : pstartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.cstartId
     *
     * @return the value of ecs_route.cstartId
     *
     * @mbg.generated
     */
    public String getCstartid() {
        return cstartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.cstartId
     *
     * @param cstartid the value for ecs_route.cstartId
     *
     * @mbg.generated
     */
    public void setCstartid(String cstartid) {
        this.cstartid = cstartid == null ? null : cstartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.pmiddleId
     *
     * @return the value of ecs_route.pmiddleId
     *
     * @mbg.generated
     */
    public String getPmiddleid() {
        return pmiddleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.pmiddleId
     *
     * @param pmiddleid the value for ecs_route.pmiddleId
     *
     * @mbg.generated
     */
    public void setPmiddleid(String pmiddleid) {
        this.pmiddleid = pmiddleid == null ? null : pmiddleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.cmiddleId
     *
     * @return the value of ecs_route.cmiddleId
     *
     * @mbg.generated
     */
    public String getCmiddleid() {
        return cmiddleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.cmiddleId
     *
     * @param cmiddleid the value for ecs_route.cmiddleId
     *
     * @mbg.generated
     */
    public void setCmiddleid(String cmiddleid) {
        this.cmiddleid = cmiddleid == null ? null : cmiddleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.pendId
     *
     * @return the value of ecs_route.pendId
     *
     * @mbg.generated
     */
    public String getPendid() {
        return pendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.pendId
     *
     * @param pendid the value for ecs_route.pendId
     *
     * @mbg.generated
     */
    public void setPendid(String pendid) {
        this.pendid = pendid == null ? null : pendid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.cendId
     *
     * @return the value of ecs_route.cendId
     *
     * @mbg.generated
     */
    public String getCendid() {
        return cendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.cendId
     *
     * @param cendid the value for ecs_route.cendId
     *
     * @mbg.generated
     */
    public void setCendid(String cendid) {
        this.cendid = cendid == null ? null : cendid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.yprice
     *
     * @return the value of ecs_route.yprice
     *
     * @mbg.generated
     */
    public Long getYprice() {
        return yprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.yprice
     *
     * @param yprice the value for ecs_route.yprice
     *
     * @mbg.generated
     */
    public void setYprice(Long yprice) {
        this.yprice = yprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_route.note
     *
     * @return the value of ecs_route.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_route.note
     *
     * @param note the value for ecs_route.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}