package com.chensheng.model;

import java.util.Date;

public class EcsVehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.vId
     *
     * @mbg.generated
     */
    private String vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.vmodel
     *
     * @mbg.generated
     */
    private String vmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.origin
     *
     * @mbg.generated
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.route
     *
     * @mbg.generated
     */
    private String route;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.productionday
     *
     * @mbg.generated
     */
    private Date productionday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.purchaseday
     *
     * @mbg.generated
     */
    private Date purchaseday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.vId
     *
     * @return the value of ecs_vehicle.vId
     *
     * @mbg.generated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.vId
     *
     * @param vid the value for ecs_vehicle.vId
     *
     * @mbg.generated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.vmodel
     *
     * @return the value of ecs_vehicle.vmodel
     *
     * @mbg.generated
     */
    public String getVmodel() {
        return vmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.vmodel
     *
     * @param vmodel the value for ecs_vehicle.vmodel
     *
     * @mbg.generated
     */
    public void setVmodel(String vmodel) {
        this.vmodel = vmodel == null ? null : vmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.origin
     *
     * @return the value of ecs_vehicle.origin
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.origin
     *
     * @param origin the value for ecs_vehicle.origin
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.route
     *
     * @return the value of ecs_vehicle.route
     *
     * @mbg.generated
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.route
     *
     * @param route the value for ecs_vehicle.route
     *
     * @mbg.generated
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.productionday
     *
     * @return the value of ecs_vehicle.productionday
     *
     * @mbg.generated
     */
    public Date getProductionday() {
        return productionday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.productionday
     *
     * @param productionday the value for ecs_vehicle.productionday
     *
     * @mbg.generated
     */
    public void setProductionday(Date productionday) {
        this.productionday = productionday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.purchaseday
     *
     * @return the value of ecs_vehicle.purchaseday
     *
     * @mbg.generated
     */
    public Date getPurchaseday() {
        return purchaseday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.purchaseday
     *
     * @param purchaseday the value for ecs_vehicle.purchaseday
     *
     * @mbg.generated
     */
    public void setPurchaseday(Date purchaseday) {
        this.purchaseday = purchaseday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.note
     *
     * @return the value of ecs_vehicle.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.note
     *
     * @param note the value for ecs_vehicle.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}